/*
 *  Copyright (C) 2010-2014 JPEXS, All rights reserved.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 */
package com.jpexs.decompiler.flash.action.parser.pcode;

import com.jpexs.decompiler.flash.action.parser.ActionParseException;
import com.jpexs.decompiler.flash.action.swf4.ConstantIndex;
import com.jpexs.decompiler.flash.action.swf4.RegisterNumber;
import com.jpexs.decompiler.flash.ecma.Null;
import com.jpexs.decompiler.flash.ecma.Undefined;

/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3 on 12.4.13 19:32 from the
 * specification file
 * <tt>D:/Dokumenty/Programovani/JavaSE/FFDec/trunk/src/com/jpexs/decompiler/flash/action/parser/pcode/flasm.flex</tt>
 */
public final class FlasmLexer {

    /**
     * This character denotes the end of file
     */
    public static final int YYEOF = -1;
    /**
     * initial size of the lookahead buffer
     */
    private static final int ZZ_BUFFERSIZE = 16384;
    /**
     * lexical states
     */
    public static final int STRING = 2;
    public static final int YYINITIAL = 0;
    public static final int PARAMETERS = 4;
    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
     * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l at the
     * beginning of a line l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = {
        0, 0, 1, 1, 2, 2
    };
    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED
            = "\11\6\1\4\1\2\1\0\1\4\1\1\16\6\4\0\1\4\1\0"
            + "\1\45\1\0\1\5\2\0\1\47\3\0\1\37\1\0\1\30\1\35"
            + "\1\0\1\33\3\50\4\40\2\11\1\12\1\3\5\0\4\7\1\36"
            + "\3\7\1\31\4\7\1\34\14\7\1\0\1\41\2\0\1\10\1\0"
            + "\1\22\1\46\1\43\1\26\1\20\1\21\1\42\1\7\1\27\2\7"
            + "\1\23\1\7\1\25\1\44\2\7\1\16\1\24\1\15\1\17\3\7"
            + "\1\32\1\7\1\13\1\0\1\14\1\0\41\6\2\0\4\5\4\0"
            + "\1\5\2\0\1\6\7\0\1\5\4\0\1\5\5\0\27\5\1\0"
            + "\37\5\1\0\u01ca\5\4\0\14\5\16\0\5\5\7\0\1\5\1\0"
            + "\1\5\21\0\160\6\5\5\1\0\2\5\2\0\4\5\10\0\1\5"
            + "\1\0\3\5\1\0\1\5\1\0\24\5\1\0\123\5\1\0\213\5"
            + "\1\0\5\6\2\0\236\5\11\0\46\5\2\0\1\5\7\0\47\5"
            + "\11\0\55\6\1\0\1\6\1\0\2\6\1\0\2\6\1\0\1\6"
            + "\10\0\33\5\5\0\3\5\15\0\4\6\7\0\1\5\4\0\13\6"
            + "\5\0\53\5\37\6\4\0\2\5\1\6\143\5\1\0\1\5\10\6"
            + "\1\0\6\6\2\5\2\6\1\0\4\6\2\5\12\6\3\5\2\0"
            + "\1\5\17\0\1\6\1\5\1\6\36\5\33\6\2\0\131\5\13\6"
            + "\1\5\16\0\12\6\41\5\11\6\2\5\4\0\1\5\5\0\26\5"
            + "\4\6\1\5\11\6\1\5\3\6\1\5\5\6\22\0\31\5\3\6"
            + "\244\0\4\6\66\5\3\6\1\5\22\6\1\5\7\6\12\5\2\6"
            + "\2\0\12\6\1\0\7\5\1\0\7\5\1\0\3\6\1\0\10\5"
            + "\2\0\2\5\2\0\26\5\1\0\7\5\1\0\1\5\3\0\4\5"
            + "\2\0\1\6\1\5\7\6\2\0\2\6\2\0\3\6\1\5\10\0"
            + "\1\6\4\0\2\5\1\0\3\5\2\6\2\0\12\6\4\5\7\0"
            + "\1\5\5\0\3\6\1\0\6\5\4\0\2\5\2\0\26\5\1\0"
            + "\7\5\1\0\2\5\1\0\2\5\1\0\2\5\2\0\1\6\1\0"
            + "\5\6\4\0\2\6\2\0\3\6\3\0\1\6\7\0\4\5\1\0"
            + "\1\5\7\0\14\6\3\5\1\6\13\0\3\6\1\0\11\5\1\0"
            + "\3\5\1\0\26\5\1\0\7\5\1\0\2\5\1\0\5\5\2\0"
            + "\1\6\1\5\10\6\1\0\3\6\1\0\3\6\2\0\1\5\17\0"
            + "\2\5\2\6\2\0\12\6\1\0\1\5\17\0\3\6\1\0\10\5"
            + "\2\0\2\5\2\0\26\5\1\0\7\5\1\0\2\5\1\0\5\5"
            + "\2\0\1\6\1\5\7\6\2\0\2\6\2\0\3\6\10\0\2\6"
            + "\4\0\2\5\1\0\3\5\2\6\2\0\12\6\1\0\1\5\20\0"
            + "\1\6\1\5\1\0\6\5\3\0\3\5\1\0\4\5\3\0\2\5"
            + "\1\0\1\5\1\0\2\5\3\0\2\5\3\0\3\5\3\0\14\5"
            + "\4\0\5\6\3\0\3\6\1\0\4\6\2\0\1\5\6\0\1\6"
            + "\16\0\12\6\11\0\1\5\7\0\3\6\1\0\10\5\1\0\3\5"
            + "\1\0\27\5\1\0\12\5\1\0\5\5\3\0\1\5\7\6\1\0"
            + "\3\6\1\0\4\6\7\0\2\6\1\0\2\5\6\0\2\5\2\6"
            + "\2\0\12\6\22\0\2\6\1\0\10\5\1\0\3\5\1\0\27\5"
            + "\1\0\12\5\1\0\5\5\2\0\1\6\1\5\7\6\1\0\3\6"
            + "\1\0\4\6\7\0\2\6\7\0\1\5\1\0\2\5\2\6\2\0"
            + "\12\6\1\0\2\5\17\0\2\6\1\0\10\5\1\0\3\5\1\0"
            + "\51\5\2\0\1\5\7\6\1\0\3\6\1\0\4\6\1\5\10\0"
            + "\1\6\10\0\2\5\2\6\2\0\12\6\12\0\6\5\2\0\2\6"
            + "\1\0\22\5\3\0\30\5\1\0\11\5\1\0\1\5\2\0\7\5"
            + "\3\0\1\6\4\0\6\6\1\0\1\6\1\0\10\6\22\0\2\6"
            + "\15\0\60\5\1\6\2\5\7\6\4\0\10\5\10\6\1\0\12\6"
            + "\47\0\2\5\1\0\1\5\2\0\2\5\1\0\1\5\2\0\1\5"
            + "\6\0\4\5\1\0\7\5\1\0\3\5\1\0\1\5\1\0\1\5"
            + "\2\0\2\5\1\0\4\5\1\6\2\5\6\6\1\0\2\6\1\5"
            + "\2\0\5\5\1\0\1\5\1\0\6\6\2\0\12\6\2\0\2\5"
            + "\42\0\1\5\27\0\2\6\6\0\12\6\13\0\1\6\1\0\1\6"
            + "\1\0\1\6\4\0\2\6\10\5\1\0\44\5\4\0\24\6\1\0"
            + "\2\6\5\5\13\6\1\0\44\6\11\0\1\6\71\0\53\5\24\6"
            + "\1\5\12\6\6\0\6\5\4\6\4\5\3\6\1\5\3\6\2\5"
            + "\7\6\3\5\4\6\15\5\14\6\1\5\17\6\2\0\46\5\12\0"
            + "\53\5\1\0\1\5\3\0\u0149\5\1\0\4\5\2\0\7\5\1\0"
            + "\1\5\1\0\4\5\2\0\51\5\1\0\4\5\2\0\41\5\1\0"
            + "\4\5\2\0\7\5\1\0\1\5\1\0\4\5\2\0\17\5\1\0"
            + "\71\5\1\0\4\5\2\0\103\5\2\0\3\6\40\0\20\5\20\0"
            + "\125\5\14\0\u026c\5\2\0\21\5\1\0\32\5\5\0\113\5\3\0"
            + "\3\5\17\0\15\5\1\0\4\5\3\6\13\0\22\5\3\6\13\0"
            + "\22\5\2\6\14\0\15\5\1\0\3\5\1\0\2\6\14\0\64\5"
            + "\40\6\3\0\1\5\3\0\2\5\1\6\2\0\12\6\41\0\3\6"
            + "\2\0\12\6\6\0\130\5\10\0\51\5\1\6\1\5\5\0\106\5"
            + "\12\0\35\5\3\0\14\6\4\0\14\6\12\0\12\6\36\5\2\0"
            + "\5\5\13\0\54\5\4\0\21\6\7\5\2\6\6\0\12\6\46\0"
            + "\27\5\5\6\4\0\65\5\12\6\1\0\35\6\2\0\13\6\6\0"
            + "\12\6\15\0\1\5\130\0\5\6\57\5\21\6\7\5\4\0\12\6"
            + "\21\0\11\6\14\0\3\6\36\5\12\6\3\0\2\5\12\6\6\0"
            + "\46\5\16\6\14\0\44\5\24\6\10\0\12\6\3\0\3\5\12\6"
            + "\44\5\122\0\3\6\1\0\25\6\4\5\1\6\4\5\1\6\15\0"
            + "\300\5\47\6\25\0\4\6\u0116\5\2\0\6\5\2\0\46\5\2\0"
            + "\6\5\2\0\10\5\1\0\1\5\1\0\1\5\1\0\1\5\1\0"
            + "\37\5\2\0\65\5\1\0\7\5\1\0\1\5\3\0\3\5\1\0"
            + "\7\5\3\0\4\5\2\0\6\5\4\0\15\5\5\0\3\5\1\0"
            + "\7\5\16\0\5\6\32\0\5\6\20\0\2\5\23\0\1\5\13\0"
            + "\5\6\5\0\6\6\1\0\1\5\15\0\1\5\20\0\15\5\3\0"
            + "\32\5\26\0\15\6\4\0\1\6\3\0\14\6\21\0\1\5\4\0"
            + "\1\5\2\0\12\5\1\0\1\5\3\0\5\5\6\0\1\5\1\0"
            + "\1\5\1\0\1\5\1\0\4\5\1\0\13\5\2\0\4\5\5\0"
            + "\5\5\4\0\1\5\21\0\51\5\u0a77\0\57\5\1\0\57\5\1\0"
            + "\205\5\6\0\4\5\3\6\16\0\46\5\12\0\66\5\11\0\1\5"
            + "\17\0\1\6\27\5\11\0\7\5\1\0\7\5\1\0\7\5\1\0"
            + "\7\5\1\0\7\5\1\0\7\5\1\0\7\5\1\0\7\5\1\0"
            + "\40\6\57\0\1\5\u01d5\0\3\5\31\0\11\5\6\6\1\0\5\5"
            + "\2\0\5\5\4\0\126\5\2\0\2\6\2\0\3\5\1\0\132\5"
            + "\1\0\4\5\5\0\51\5\3\0\136\5\21\0\33\5\65\0\20\5"
            + "\u0200\0\u19b6\5\112\0\u51cc\5\64\0\u048d\5\103\0\56\5\2\0\u010d\5"
            + "\3\0\20\5\12\6\2\5\24\0\57\5\1\6\14\0\2\6\1\0"
            + "\31\5\10\0\120\5\2\6\45\0\11\5\2\0\147\5\2\0\4\5"
            + "\1\0\2\5\16\0\12\5\120\0\10\5\1\6\3\5\1\6\4\5"
            + "\1\6\27\5\5\6\20\0\1\5\7\0\64\5\14\0\2\6\62\5"
            + "\21\6\13\0\12\6\6\0\22\6\6\5\3\0\1\5\4\0\12\6"
            + "\34\5\10\6\2\0\27\5\15\6\14\0\35\5\3\0\4\6\57\5"
            + "\16\6\16\0\1\5\12\6\46\0\51\5\16\6\11\0\3\5\1\6"
            + "\10\5\2\6\2\0\12\6\6\0\27\5\3\0\1\5\1\6\4\0"
            + "\60\5\1\6\1\5\3\6\2\5\2\6\5\5\2\6\1\5\1\6"
            + "\1\5\30\0\3\5\43\0\6\5\2\0\6\5\2\0\6\5\11\0"
            + "\7\5\1\0\7\5\221\0\43\5\10\6\1\0\2\6\2\0\12\6"
            + "\6\0\u2ba4\5\14\0\27\5\4\0\61\5\u2104\0\u012e\5\2\0\76\5"
            + "\2\0\152\5\46\0\7\5\14\0\5\5\5\0\1\5\1\6\12\5"
            + "\1\0\15\5\1\0\5\5\1\0\1\5\1\0\2\5\1\0\2\5"
            + "\1\0\154\5\41\0\u016b\5\22\0\100\5\2\0\66\5\50\0\15\5"
            + "\3\0\20\6\20\0\7\6\14\0\2\5\30\0\3\5\31\0\1\5"
            + "\6\0\5\5\1\0\207\5\2\0\1\6\4\0\1\5\13\0\12\6"
            + "\7\0\32\5\4\0\1\5\1\0\32\5\13\0\131\5\3\0\6\5"
            + "\2\0\6\5\2\0\6\5\2\0\3\5\3\0\2\5\3\0\2\5"
            + "\22\0\3\6\4\0";
    /**
     * Translates characters to character classes
     */
    private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);
    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();
    private static final String ZZ_ACTION_PACKED_0
            = "\3\0\3\1\1\2\1\3\1\4\2\5\1\1\1\6"
            + "\2\7\1\10\1\11\1\12\1\13\5\11\1\1\1\11"
            + "\1\12\1\11\1\1\1\11\1\14\1\0\1\15\1\16"
            + "\1\17\1\20\1\21\1\22\2\23\1\24\1\25\1\26"
            + "\1\27\1\0\1\30\5\11\1\12\1\0\1\12\1\11"
            + "\1\30\2\11\1\23\1\30\1\0\5\11\1\0\1\11"
            + "\1\30\1\11\1\31\3\11\1\32\1\0\4\11\1\33"
            + "\1\0\4\11\1\0\4\11\1\0\4\11\1\0\1\11"
            + "\2\34\1\35\1\30\2\36";

    private static int[] zzUnpackAction() {
        int[] result = new int[104];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */

        int j = offset;  /* index in unpacked array */

        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }
    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();
    private static final String ZZ_ROWMAP_PACKED_0
            = "\0\0\0\51\0\122\0\173\0\244\0\315\0\366\0\173"
            + "\0\u011f\0\u0148\0\173\0\u0171\0\173\0\u019a\0\173\0\u01c3"
            + "\0\u01ec\0\u0215\0\173\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2"
            + "\0\u030b\0\u0334\0\u035d\0\u0386\0\u03af\0\u03d8\0\173\0\315"
            + "\0\173\0\173\0\173\0\173\0\173\0\173\0\u0401\0\u042a"
            + "\0\173\0\173\0\173\0\173\0\u0453\0\u047c\0\u04a5\0\u04ce"
            + "\0\u04f7\0\u0520\0\u0549\0\u0572\0\u059b\0\173\0\u05c4\0\u035d"
            + "\0\u05ed\0\u0616\0\173\0\u063f\0\u063f\0\u0668\0\u0691\0\u06ba"
            + "\0\u06e3\0\u070c\0\u0735\0\u075e\0\u01ec\0\u0787\0\u01ec\0\u07b0"
            + "\0\u07d9\0\u0802\0\u01ec\0\u082b\0\u0854\0\u087d\0\u08a6\0\u08cf"
            + "\0\u01ec\0\u08f8\0\u0921\0\u094a\0\u0973\0\u099c\0\u09c5\0\u09ee"
            + "\0\u0a17\0\u0a40\0\u0a69\0\u0a92\0\u0abb\0\u0ae4\0\u0b0d\0\u0b36"
            + "\0\u0b5f\0\u0b88\0\u0bb1\0\u01ec\0\u01ec\0\173\0\u0bda\0\u01ec";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[104];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;  /* index in packed string  */

        int j = offset;  /* index in unpacked array */

        int l = packed.length();
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }
    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();
    private static final String ZZ_TRANS_PACKED_0
            = "\4\4\1\5\1\6\1\4\1\7\1\6\3\4\1\10"
            + "\13\7\1\4\2\7\1\4\1\7\1\4\1\7\3\4"
            + "\3\7\1\4\1\7\2\4\1\11\1\12\1\13\36\11"
            + "\1\14\3\11\1\15\3\11\1\4\1\16\1\17\1\20"
            + "\1\4\1\21\1\4\2\21\1\22\1\4\1\23\1\4"
            + "\1\24\1\25\1\26\1\21\1\27\3\21\1\30\2\21"
            + "\1\31\1\32\1\21\1\33\1\34\1\35\1\21\1\4"
            + "\1\22\1\4\1\21\1\36\1\21\1\37\1\21\1\4"
            + "\1\22\55\0\1\5\51\0\5\40\1\41\2\0\13\40"
            + "\1\0\4\40\1\0\1\40\1\0\1\40\1\0\3\40"
            + "\1\0\1\40\1\0\1\40\5\0\2\40\3\7\1\41"
            + "\2\0\13\7\1\0\4\7\1\0\1\7\1\0\1\7"
            + "\1\0\3\7\1\0\1\7\1\0\1\7\1\11\2\0"
            + "\36\11\1\0\3\11\1\0\3\11\2\0\1\13\46\0"
            + "\2\42\1\0\12\42\1\43\1\44\2\42\1\45\3\42"
            + "\1\46\5\42\1\47\4\42\1\50\1\51\3\42\1\52"
            + "\1\53\1\54\1\47\2\0\1\17\46\0\1\20\2\0"
            + "\46\20\5\0\5\21\3\0\13\21\1\0\4\21\1\0"
            + "\1\21\1\0\1\21\1\0\3\21\1\0\1\21\1\0"
            + "\1\21\11\0\1\22\6\0\1\55\12\0\1\22\1\0"
            + "\1\56\1\55\1\0\1\22\7\0\1\22\5\0\5\21"
            + "\3\0\1\21\1\57\11\21\1\0\4\21\1\0\1\21"
            + "\1\0\1\21\1\0\3\21\1\0\1\21\1\0\1\21"
            + "\5\0\5\21\3\0\3\21\1\60\7\21\1\0\4\21"
            + "\1\0\1\21\1\0\1\21\1\0\3\21\1\0\1\21"
            + "\1\0\1\21\5\0\5\21\3\0\10\21\1\61\2\21"
            + "\1\0\4\21\1\0\1\21\1\0\1\21\1\0\3\21"
            + "\1\0\1\21\1\0\1\21\5\0\5\21\3\0\5\21"
            + "\1\62\5\21\1\0\4\21\1\0\1\21\1\0\1\21"
            + "\1\0\3\21\1\0\1\21\1\0\1\21\5\0\5\21"
            + "\3\0\2\21\1\63\10\21\1\0\4\21\1\0\1\21"
            + "\1\0\1\21\1\0\3\21\1\0\1\21\1\0\1\21"
            + "\11\0\1\64\17\0\1\65\1\0\1\66\4\0\1\64"
            + "\7\0\1\64\5\0\5\21\3\0\10\21\1\67\2\21"
            + "\1\0\4\21\1\0\1\21\1\0\1\21\1\0\3\21"
            + "\1\0\1\21\1\0\1\21\11\0\1\70\6\0\1\55"
            + "\12\0\1\70\1\0\1\56\1\55\1\0\1\70\7\0"
            + "\1\70\5\0\5\21\3\0\5\21\1\71\5\21\1\0"
            + "\4\21\1\0\1\21\1\0\1\21\1\0\3\21\1\0"
            + "\1\21\1\0\1\21\11\0\1\56\21\0\1\56\4\0"
            + "\1\56\7\0\1\56\5\0\5\21\3\0\13\21\1\0"
            + "\4\21\1\0\1\21\1\0\1\21\1\0\2\21\1\72"
            + "\1\0\1\21\1\0\1\21\33\0\1\50\4\0\1\50"
            + "\7\0\1\50\33\0\1\73\4\0\1\73\7\0\1\73"
            + "\11\0\1\74\16\0\1\75\2\0\1\74\3\0\1\75"
            + "\1\74\7\0\1\74\11\0\1\56\6\0\1\55\12\0"
            + "\1\56\2\0\1\55\1\0\1\56\7\0\1\56\5\0"
            + "\5\21\3\0\2\21\1\76\10\21\1\0\4\21\1\0"
            + "\1\21\1\0\1\21\1\0\3\21\1\0\1\21\1\0"
            + "\1\21\5\0\5\21\3\0\13\21\1\0\4\21\1\0"
            + "\1\21\1\0\1\21\1\0\1\77\2\21\1\0\1\21"
            + "\1\0\1\21\5\0\5\21\3\0\11\21\1\100\1\21"
            + "\1\0\4\21\1\0\1\21\1\0\1\21\1\0\3\21"
            + "\1\0\1\21\1\0\1\21\5\0\5\21\3\0\6\21"
            + "\1\101\4\21\1\0\4\21\1\0\1\21\1\0\1\21"
            + "\1\0\3\21\1\0\1\21\1\0\1\21\5\0\5\21"
            + "\3\0\6\21\1\102\4\21\1\0\4\21\1\0\1\21"
            + "\1\0\1\21\1\0\3\21\1\0\1\21\1\0\1\21"
            + "\11\0\1\64\21\0\1\64\4\0\1\64\7\0\1\64"
            + "\25\0\1\103\30\0\5\21\3\0\4\21\1\104\6\21"
            + "\1\0\4\21\1\0\1\21\1\0\1\21\1\0\3\21"
            + "\1\0\1\21\1\0\1\21\5\0\5\21\3\0\13\21"
            + "\1\0\3\21\1\105\1\0\1\21\1\0\1\21\1\0"
            + "\3\21\1\0\1\21\1\0\1\21\5\0\5\21\3\0"
            + "\10\21\1\106\2\21\1\0\4\21\1\0\1\21\1\0"
            + "\1\21\1\0\3\21\1\0\1\21\1\0\1\21\11\0"
            + "\1\74\21\0\1\74\4\0\1\74\7\0\1\74\5\0"
            + "\5\21\3\0\3\21\1\107\7\21\1\0\4\21\1\0"
            + "\1\21\1\0\1\21\1\0\3\21\1\0\1\21\1\0"
            + "\1\21\5\0\5\21\3\0\12\21\1\110\1\0\4\21"
            + "\1\0\1\21\1\0\1\21\1\0\3\21\1\0\1\21"
            + "\1\0\1\21\5\0\5\21\3\0\3\21\1\111\7\21"
            + "\1\0\4\21\1\0\1\21\1\0\1\21\1\0\3\21"
            + "\1\0\1\21\1\0\1\21\5\0\5\21\3\0\7\21"
            + "\1\112\3\21\1\0\4\21\1\0\1\21\1\0\1\21"
            + "\1\0\3\21\1\0\1\21\1\0\1\21\5\0\5\21"
            + "\3\0\6\21\1\113\4\21\1\0\4\21\1\0\1\21"
            + "\1\0\1\21\1\0\3\21\1\0\1\21\1\0\1\21"
            + "\21\0\1\114\34\0\5\21\3\0\12\21\1\115\1\0"
            + "\4\21\1\0\1\21\1\0\1\21\1\0\3\21\1\0"
            + "\1\21\1\0\1\21\5\0\5\21\3\0\7\21\1\116"
            + "\3\21\1\0\4\21\1\0\1\21\1\0\1\21\1\0"
            + "\3\21\1\0\1\21\1\0\1\21\5\0\5\21\3\0"
            + "\7\21\1\117\3\21\1\0\4\21\1\0\1\21\1\0"
            + "\1\21\1\0\3\21\1\0\1\21\1\0\1\21\5\0"
            + "\5\21\3\0\4\21\1\120\6\21\1\0\4\21\1\0"
            + "\1\21\1\0\1\21\1\0\3\21\1\0\1\21\1\0"
            + "\1\21\5\0\5\21\3\0\3\21\1\121\7\21\1\0"
            + "\4\21\1\0\1\21\1\0\1\21\1\0\3\21\1\0"
            + "\1\21\1\0\1\21\27\0\1\122\26\0\5\21\3\0"
            + "\10\21\1\123\2\21\1\0\4\21\1\0\1\21\1\0"
            + "\1\21\1\0\3\21\1\0\1\21\1\0\1\21\5\0"
            + "\5\21\3\0\1\124\12\21\1\0\4\21\1\0\1\21"
            + "\1\0\1\21\1\0\3\21\1\0\1\21\1\0\1\21"
            + "\5\0\5\21\3\0\1\125\12\21\1\0\4\21\1\0"
            + "\1\21\1\0\1\21\1\0\3\21\1\0\1\21\1\0"
            + "\1\21\5\0\5\21\3\0\12\21\1\126\1\0\4\21"
            + "\1\0\1\21\1\0\1\21\1\0\3\21\1\0\1\21"
            + "\1\0\1\21\25\0\1\127\30\0\5\21\3\0\12\21"
            + "\1\130\1\0\4\21\1\0\1\21\1\0\1\21\1\0"
            + "\3\21\1\0\1\21\1\0\1\21\5\0\5\21\3\0"
            + "\5\21\1\131\5\21\1\0\4\21\1\0\1\21\1\0"
            + "\1\21\1\0\3\21\1\0\1\21\1\0\1\21\5\0"
            + "\5\21\3\0\3\21\1\132\7\21\1\0\4\21\1\0"
            + "\1\21\1\0\1\21\1\0\3\21\1\0\1\21\1\0"
            + "\1\21\5\0\5\21\3\0\10\21\1\133\2\21\1\0"
            + "\4\21\1\0\1\21\1\0\1\21\1\0\3\21\1\0"
            + "\1\21\1\0\1\21\27\0\1\134\26\0\5\21\3\0"
            + "\1\135\12\21\1\0\4\21\1\0\1\21\1\0\1\21"
            + "\1\0\3\21\1\0\1\21\1\0\1\21\5\0\5\21"
            + "\3\0\10\21\1\136\2\21\1\0\4\21\1\0\1\21"
            + "\1\0\1\21\1\0\3\21\1\0\1\21\1\0\1\21"
            + "\5\0\5\21\3\0\1\21\1\137\11\21\1\0\4\21"
            + "\1\0\1\21\1\0\1\21\1\0\3\21\1\0\1\21"
            + "\1\0\1\21\5\0\5\21\3\0\3\21\1\140\7\21"
            + "\1\0\4\21\1\0\1\21\1\0\1\21\1\0\3\21"
            + "\1\0\1\21\1\0\1\21\15\0\1\141\40\0\5\21"
            + "\3\0\13\21\1\0\1\21\1\105\2\21\1\0\1\21"
            + "\1\0\1\21\1\0\3\21\1\0\1\21\1\0\1\21"
            + "\5\0\5\21\3\0\1\142\12\21\1\0\4\21\1\0"
            + "\1\21\1\0\1\21\1\0\3\21\1\0\1\21\1\0"
            + "\1\21\5\0\4\21\1\143\3\0\13\21\1\0\2\21"
            + "\1\144\1\21\1\0\1\21\1\0\1\143\1\0\3\21"
            + "\1\0\1\21\1\0\1\143\5\0\5\21\3\0\11\21"
            + "\1\145\1\21\1\0\4\21\1\0\1\21\1\0\1\21"
            + "\1\0\3\21\1\0\1\21\1\0\1\21\32\0\1\146"
            + "\23\0\4\21\1\147\3\0\13\21\1\0\2\21\1\150"
            + "\1\21\1\0\1\21\1\0\1\147\1\0\3\21\1\0"
            + "\1\21\1\0\1\147\5\0\4\21\1\143\3\0\13\21"
            + "\1\0\2\21\1\143\1\21\1\0\1\21\1\0\1\143"
            + "\1\0\3\21\1\0\1\21\1\0\1\143\5\0\4\21"
            + "\1\147\3\0\13\21\1\0\2\21\1\147\1\21\1\0"
            + "\1\21\1\0\1\147\1\0\3\21\1\0\1\21\1\0"
            + "\1\147";

    private static int[] zzUnpackTrans() {
        int[] result = new int[3075];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */

        int j = offset;  /* index in unpacked array */

        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }
    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = {
        "Unkown internal scanner error",
        "Error: could not match input",
        "Error: pushback value was too large"
    };
    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();
    private static final String ZZ_ATTRIBUTE_PACKED_0
            = "\3\0\1\11\3\1\1\11\2\1\1\11\1\1\1\11"
            + "\1\1\1\11\3\1\1\11\13\1\1\11\1\0\6\11"
            + "\2\1\4\11\1\0\7\1\1\0\1\11\4\1\1\11"
            + "\1\1\1\0\5\1\1\0\10\1\1\0\5\1\1\0"
            + "\4\1\1\0\4\1\1\0\4\1\1\0\4\1\1\11"
            + "\2\1";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[104];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */

        int j = offset;  /* index in unpacked array */

        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }
    /**
     * the input device
     */
    private java.io.Reader zzReader;
    /**
     * the current state of the DFA
     */
    private int zzState;
    /**
     * the current lexical state
     */
    private int zzLexicalState = YYINITIAL;
    /**
     * this buffer contains the current text to be matched and is the source of
     * the yytext() string
     */
    private char zzBuffer[] = new char[ZZ_BUFFERSIZE];
    /**
     * the textposition at the last accepting state
     */
    private int zzMarkedPos;
    /**
     * the current text position in the buffer
     */
    private int zzCurrentPos;
    /**
     * startRead marks the beginning of the yytext() string in the buffer
     */
    private int zzStartRead;
    /**
     * endRead marks the last character in the buffer, that has been read from
     * input
     */
    private int zzEndRead;
    /**
     * number of newlines encountered up to the start of the matched text
     */
    private int yyline;
    /**
     * the number of characters up to the start of the matched text
     */
    private int yychar;
    /**
     * the number of characters from the last newline up to the start of the
     * matched text
     */
    private int yycolumn;
    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;
    /**
     * zzAtEOF == true <=> the scanner is at the EOF
     */
    private boolean zzAtEOF;
    /**
     * denotes if the user-EOF-code has already been executed
     */
    private boolean zzEOFDone;

    /* user code: */
    StringBuffer string = new StringBuffer();

    /**
     * Create an empty lexer, yyrset will be called later to reset and assign
     * the reader
     */
    public FlasmLexer() {
    }

    public int yychar() {
        return yychar;
    }

    public int yyline() {
        return yyline + 1;
    }

    /**
     * Creates a new scanner There is also a java.io.InputStream version of this
     * constructor.
     *
     * @param in the java.io.Reader to read input from.
     */
    public FlasmLexer(java.io.Reader in) {
        this.zzReader = in;
    }

    /**
     * Creates a new scanner. There is also java.io.Reader version of this
     * constructor.
     *
     * @param in the java.io.Inputstream to read input from.
     */
    public FlasmLexer(java.io.InputStream in) {
        this(new java.io.InputStreamReader(in));
    }

    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed the packed character translation table
     * @return the unpacked character translation table
     */
    private static char[] zzUnpackCMap(String packed) {
        char[] map = new char[0x10000];
        int i = 0;  /* index in packed string  */

        int j = 0;  /* index in unpacked array */

        while (i < 2206) {
            int count = packed.charAt(i++);
            char value = packed.charAt(i++);
            do {
                map[j++] = value;
            } while (--count > 0);
        }
        return map;
    }

    /**
     * Refills the input buffer.
     *
     * @return      <code>false</code>, iff there was new input.
     *
     * @exception java.io.IOException if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {

        /* first: make room (if you can) */
        if (zzStartRead > 0) {
            System.arraycopy(zzBuffer, zzStartRead,
                    zzBuffer, 0,
                    zzEndRead - zzStartRead);

            /* translate stored positions */
            zzEndRead -= zzStartRead;
            zzCurrentPos -= zzStartRead;
            zzMarkedPos -= zzStartRead;
            zzStartRead = 0;
        }

        /* is the buffer big enough? */
        if (zzCurrentPos >= zzBuffer.length) {
            /* if not: blow it up */
            char newBuffer[] = new char[zzCurrentPos * 2];
            System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
            zzBuffer = newBuffer;
        }

        /* finally: fill the buffer with new input */
        int numRead = zzReader.read(zzBuffer, zzEndRead,
                zzBuffer.length - zzEndRead);

        if (numRead > 0) {
            zzEndRead += numRead;
            return false;
        }
        // unlikely but not impossible: read 0 characters, but not at end of stream    
        if (numRead == 0) {
            int c = zzReader.read();
            if (c == -1) {
                return true;
            } else {
                zzBuffer[zzEndRead++] = (char) c;
                return false;
            }
        }

        // numRead < 0
        return true;
    }

    /**
     * Closes the input stream.
     *
     * @throws java.io.IOException
     */
    public final void yyclose() throws java.io.IOException {
        zzAtEOF = true;            /* indicate end of file */

        zzEndRead = zzStartRead;  /* invalidate buffer    */

        if (zzReader != null) {
            zzReader.close();
        }
    }

    /**
     * Resets the scanner to read from a new input stream. Does not close the
     * old reader.
     *
     * All internal variables are reset, the old input stream
     * <b>cannot</b> be reused (internal buffer is discarded and lost). Lexical
     * state is set to <tt>ZZ_INITIAL</tt>.
     *
     * @param reader the new input stream
     */
    public final void yyreset(java.io.Reader reader) {
        zzReader = reader;
        zzAtBOL = true;
        zzAtEOF = false;
        zzEOFDone = false;
        zzEndRead = zzStartRead = 0;
        zzCurrentPos = zzMarkedPos = 0;
        yyline = yychar = yycolumn = 0;
        zzLexicalState = YYINITIAL;
    }

    /**
     * Returns the current lexical state.
     *
     * @return
     */
    public final int yystate() {
        return zzLexicalState;
    }

    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }

    /**
     * Returns the text matched by the current regular expression.
     *
     * @return
     */
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }

    /**
     * Returns the character at position <tt>pos</tt> from the matched text.
     *
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch. A value from 0 to
     * yylength()-1.
     *
     * @return the character at position pos
     */
    public final char yycharat(int pos) {
        return zzBuffer[zzStartRead + pos];
    }

    /**
     * Returns the length of the matched text region.
     *
     * @return
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }

    /**
     * Reports an error that occured while scanning.
     *
     * In a wellformed scanner (no or only correct usage of yypushback(int) and
     * a match-all fallback rule) this method will only be called with things
     * that "Can't Possibly Happen". If this method is called, something is
     * seriously wrong (e.g. a JFlex bug producing a faulty scanner etc.).
     *
     * Usual syntax/scanner level error handling should be done in error
     * fallback rules.
     *
     * @param errorCode the code of the errormessage to display
     */
    private void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }

    /**
     * Pushes the specified amount of characters back into the input stream.
     *
     * They will be read again by then next call of the scanning method
     *
     * @param number the number of characters to be read again. This number must
     * not be greater than yylength()!
     */
    public void yypushback(int number) {
        if (number > yylength()) {
            zzScanError(ZZ_PUSHBACK_2BIG);
        }

        zzMarkedPos -= number;
    }

    /**
     * Resumes scanning until the next regular expression is matched, the end of
     * input is encountered or an I/O-Error occurs.
     *
     * @return the next token
     * @exception java.io.IOException if any I/O-Error occurs
     * @throws com.jpexs.decompiler.flash.action.parser.ActionParseException
     */
    public ASMParsedSymbol yylex() throws java.io.IOException, ActionParseException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;
        char[] zzCMapL = ZZ_CMAP;

        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            yychar += zzMarkedPosL - zzStartRead;

            boolean zzR = false;
            for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                    zzCurrentPosL++) {
                switch (zzBufferL[zzCurrentPosL]) {
                    case '\u000B':
                    case '\u000C':
                    case '\u0085':
                    case '\u2028':
                    case '\u2029':
                        yyline++;
                        yycolumn = 0;
                        zzR = false;
                        break;
                    case '\r':
                        yyline++;
                        yycolumn = 0;
                        zzR = true;
                        break;
                    case '\n':
                        if (zzR) {
                            zzR = false;
                        } else {
                            yyline++;
                            yycolumn = 0;
                        }
                        break;
                    default:
                        zzR = false;
                        yycolumn++;
                }
            }

            if (zzR) {
                // peek one character ahead if it is \n (if we have counted one line too much)
                boolean zzPeek;
                if (zzMarkedPosL < zzEndReadL) {
                    zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                } else if (zzAtEOF) {
                    zzPeek = false;
                } else {
                    boolean eof = zzRefill();
                    zzEndReadL = zzEndRead;
                    zzMarkedPosL = zzMarkedPos;
                    zzBufferL = zzBuffer;
                    if (eof) {
                        zzPeek = false;
                    } else {
                        zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                    }
                }
                if (zzPeek) {
                    yyline--;
                }
            }
            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];

            zzForAction:
            {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = zzBufferL[zzCurrentPosL++];
                    } else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = zzBufferL[zzCurrentPosL++];
                        }
                    }
                    int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput]];
                    if (zzNext == -1) {
                        break zzForAction;
                    }
                    zzState = zzNext;

                    int zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) {
                            break zzForAction;
                        }
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                case 23: {
                    string.append('\'');
                }
                case 31:
                    break;
                case 25: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_BOOLEAN, Boolean.TRUE);
                }
                case 32:
                    break;
                case 19: {
                    char val = (char) Integer.parseInt(yytext().substring(1), 8);
                    string.append(val);
                }
                case 33:
                    break;
                case 4: {
                    string.append(yytext());
                }
                case 34:
                    break;
                case 7: {
                    yybegin(YYINITIAL);
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_EOL);
                }
                case 35:
                    break;
                case 16: {
                    string.append('\r');
                }
                case 36:
                    break;
                case 12: {
                    yybegin(STRING);
                    string.setLength(0);
                }
                case 37:
                    break;
                case 26: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_NULL, new Null());
                }
                case 38:
                    break;
                case 3: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_BLOCK_END);
                }
                case 39:
                    break;
                case 30: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_CONSTANT, new ConstantIndex(Integer.parseInt(yytext().substring(8))));
                }
                case 40:
                    break;
                case 22: {
                    string.append('\b');
                }
                case 41:
                    break;
                case 9: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_IDENTIFIER, yytext());
                }
                case 42:
                    break;
                case 5: {
                    throw new ActionParseException("Unterminated string at end of line", yyline + 1);
                }
                case 43:
                    break;
                case 27: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_BOOLEAN, Boolean.FALSE);
                }
                case 44:
                    break;
                case 24: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_FLOAT, Double.parseDouble((yytext())));
                }
                case 45:
                    break;
                case 15: {
                    string.append('\t');
                }
                case 46:
                    break;
                case 6: {
                    yybegin(PARAMETERS);
                    // length also includes the trailing quote
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_STRING, string.toString());
                }
                case 47:
                    break;
                case 2: {
                    yybegin(PARAMETERS);
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_INSTRUCTION_NAME, yytext());
                }
                case 48:
                    break;
                case 28: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_REGISTER, new RegisterNumber(Integer.parseInt(yytext().substring(8))));
                }
                case 49:
                    break;
                case 13: {
                    String s = yytext();
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_LABEL, s.substring(0, s.length() - 1));
                }
                case 50:
                    break;
                case 20: {
                    string.append('\\');
                }
                case 51:
                    break;
                case 14: {
                    throw new ActionParseException("Illegal escape sequence \"" + yytext() + "\"", yyline + 1);
                }
                case 52:
                    break;
                case 29: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_UNDEFINED, new Undefined());
                }
                case 53:
                    break;
                case 18: {
                    string.append('\n');
                }
                case 54:
                    break;
                case 10: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_INTEGER, Long.parseLong((yytext())));
                }
                case 55:
                    break;
                case 17: {
                    string.append('\f');
                }
                case 56:
                    break;
                case 8: {
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_COMMENT, yytext().substring(1));
                }
                case 57:
                    break;
                case 11: {
                    yybegin(YYINITIAL);
                    return new ASMParsedSymbol(ASMParsedSymbol.TYPE_BLOCK_START);
                }
                case 58:
                    break;
                case 21: {
                    string.append('\"');
                }
                case 59:
                    break;
                case 1: {
                }
                case 60:
                    break;
                default:
                    if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                        zzAtEOF = true;
                        {
                            return new ASMParsedSymbol(ASMParsedSymbol.TYPE_EOF);
                        }
                    } else {
                        zzScanError(ZZ_NO_MATCH);
                    }
            }
        }
    }
}
