/* The following code was generated by JFlex 1.4.3 on 18.8.10 12:17 */

/* Flash assembler language lexer specification */

package com.jpexs.asdec.abc.avm2.parser;


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 18.8.10 12:17 from the specification file
 * <tt>D:/Dokumenty/Programovani/JavaSE/ASDec/trunk/src/com/jpexs/asdec/abc/avm2/parser/flasm3.flex</tt>
 */
public final class Flasm3Lexer {

    /**
     * This character denotes the end of file
     */
    public static final int YYEOF = -1;

    /**
     * initial size of the lookahead buffer
     */
    private static final int ZZ_BUFFERSIZE = 16384;

    /**
     * lexical states
     */
    public static final int STRING = 2;
    public static final int YYINITIAL = 0;
    public static final int PARAMETERS = 4;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
     * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
     * at the beginning of a line
     * l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = {
            0, 0, 1, 1, 2, 2
    };

    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED =
            "\11\12\1\4\1\2\1\0\1\4\1\1\16\12\4\0\1\4\1\0" +
                    "\1\26\1\0\1\11\2\0\1\34\3\0\1\23\1\0\1\17\1\20" +
                    "\1\0\1\16\3\35\4\24\2\7\1\15\1\3\5\0\4\11\1\21" +
                    "\25\11\1\6\1\25\1\10\1\0\1\14\1\0\1\13\1\27\2\13" +
                    "\1\22\1\32\6\13\1\5\1\31\3\13\1\33\1\13\1\30\6\13" +
                    "\4\0\41\12\2\0\4\11\4\0\1\11\2\0\1\12\7\0\1\11" +
                    "\4\0\1\11\5\0\27\11\1\0\37\11\1\0\u013f\11\31\0\162\11" +
                    "\4\0\14\11\16\0\5\11\11\0\1\11\21\0\130\12\5\0\23\12" +
                    "\12\0\1\11\13\0\1\11\1\0\3\11\1\0\1\11\1\0\24\11" +
                    "\1\0\54\11\1\0\46\11\1\0\5\11\4\0\202\11\1\0\4\12" +
                    "\3\0\105\11\1\0\46\11\2\0\2\11\6\0\20\11\41\0\46\11" +
                    "\2\0\1\11\7\0\47\11\11\0\21\12\1\0\27\12\1\0\3\12" +
                    "\1\0\1\12\1\0\2\12\1\0\1\12\13\0\33\11\5\0\3\11" +
                    "\15\0\4\12\14\0\6\12\13\0\32\11\5\0\13\11\16\12\7\0" +
                    "\12\12\4\0\2\11\1\12\143\11\1\0\1\11\10\12\1\0\6\12" +
                    "\2\11\2\12\1\0\4\12\2\11\12\12\3\11\2\0\1\11\17\0" +
                    "\1\12\1\11\1\12\36\11\33\12\2\0\3\11\60\0\46\11\13\12" +
                    "\1\11\u014f\0\3\12\66\11\2\0\1\12\1\11\20\12\2\0\1\11" +
                    "\4\12\3\0\12\11\2\12\2\0\12\12\21\0\3\12\1\0\10\11" +
                    "\2\0\2\11\2\0\26\11\1\0\7\11\1\0\1\11\3\0\4\11" +
                    "\2\0\1\12\1\11\7\12\2\0\2\12\2\0\3\12\11\0\1\12" +
                    "\4\0\2\11\1\0\3\11\2\12\2\0\12\12\4\11\15\0\3\12" +
                    "\1\0\6\11\4\0\2\11\2\0\26\11\1\0\7\11\1\0\2\11" +
                    "\1\0\2\11\1\0\2\11\2\0\1\12\1\0\5\12\4\0\2\12" +
                    "\2\0\3\12\13\0\4\11\1\0\1\11\7\0\14\12\3\11\14\0" +
                    "\3\12\1\0\11\11\1\0\3\11\1\0\26\11\1\0\7\11\1\0" +
                    "\2\11\1\0\5\11\2\0\1\12\1\11\10\12\1\0\3\12\1\0" +
                    "\3\12\2\0\1\11\17\0\2\11\2\12\2\0\12\12\1\0\1\11" +
                    "\17\0\3\12\1\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11" +
                    "\1\0\2\11\1\0\5\11\2\0\1\12\1\11\6\12\3\0\2\12" +
                    "\2\0\3\12\10\0\2\12\4\0\2\11\1\0\3\11\4\0\12\12" +
                    "\1\0\1\11\20\0\1\12\1\11\1\0\6\11\3\0\3\11\1\0" +
                    "\4\11\3\0\2\11\1\0\1\11\1\0\2\11\3\0\2\11\3\0" +
                    "\3\11\3\0\10\11\1\0\3\11\4\0\5\12\3\0\3\12\1\0" +
                    "\4\12\11\0\1\12\17\0\11\12\11\0\1\11\7\0\3\12\1\0" +
                    "\10\11\1\0\3\11\1\0\27\11\1\0\12\11\1\0\5\11\4\0" +
                    "\7\12\1\0\3\12\1\0\4\12\7\0\2\12\11\0\2\11\4\0" +
                    "\12\12\22\0\2\12\1\0\10\11\1\0\3\11\1\0\27\11\1\0" +
                    "\12\11\1\0\5\11\2\0\1\12\1\11\7\12\1\0\3\12\1\0" +
                    "\4\12\7\0\2\12\7\0\1\11\1\0\2\11\4\0\12\12\22\0" +
                    "\2\12\1\0\10\11\1\0\3\11\1\0\27\11\1\0\20\11\4\0" +
                    "\6\12\2\0\3\12\1\0\4\12\11\0\1\12\10\0\2\11\4\0" +
                    "\12\12\22\0\2\12\1\0\22\11\3\0\30\11\1\0\11\11\1\0" +
                    "\1\11\2\0\7\11\3\0\1\12\4\0\6\12\1\0\1\12\1\0" +
                    "\10\12\22\0\2\12\15\0\60\11\1\12\2\11\7\12\4\0\10\11" +
                    "\10\12\1\0\12\12\47\0\2\11\1\0\1\11\2\0\2\11\1\0" +
                    "\1\11\2\0\1\11\6\0\4\11\1\0\7\11\1\0\3\11\1\0" +
                    "\1\11\1\0\1\11\2\0\2\11\1\0\4\11\1\12\2\11\6\12" +
                    "\1\0\2\12\1\11\2\0\5\11\1\0\1\11\1\0\6\12\2\0" +
                    "\12\12\2\0\2\11\42\0\1\11\27\0\2\12\6\0\12\12\13\0" +
                    "\1\12\1\0\1\12\1\0\1\12\4\0\2\12\10\11\1\0\42\11" +
                    "\6\0\24\12\1\0\2\12\4\11\4\0\10\12\1\0\44\12\11\0" +
                    "\1\12\71\0\42\11\1\0\5\11\1\0\2\11\1\0\7\12\3\0" +
                    "\4\12\6\0\12\12\6\0\6\11\4\12\106\0\46\11\12\0\51\11" +
                    "\7\0\132\11\5\0\104\11\5\0\122\11\6\0\7\11\1\0\77\11" +
                    "\1\0\1\11\1\0\4\11\2\0\7\11\1\0\1\11\1\0\4\11" +
                    "\2\0\47\11\1\0\1\11\1\0\4\11\2\0\37\11\1\0\1\11" +
                    "\1\0\4\11\2\0\7\11\1\0\1\11\1\0\4\11\2\0\7\11" +
                    "\1\0\7\11\1\0\27\11\1\0\37\11\1\0\1\11\1\0\4\11" +
                    "\2\0\7\11\1\0\47\11\1\0\23\11\16\0\11\12\56\0\125\11" +
                    "\14\0\u026c\11\2\0\10\11\12\0\32\11\5\0\113\11\3\0\3\11" +
                    "\17\0\15\11\1\0\4\11\3\12\13\0\22\11\3\12\13\0\22\11" +
                    "\2\12\14\0\15\11\1\0\3\11\1\0\2\12\14\0\64\11\40\12" +
                    "\3\0\1\11\3\0\2\11\1\12\2\0\12\12\41\0\3\12\2\0" +
                    "\12\12\6\0\130\11\10\0\51\11\1\12\126\0\35\11\3\0\14\12" +
                    "\4\0\14\12\12\0\12\12\36\11\2\0\5\11\u038b\0\154\11\224\0" +
                    "\234\11\4\0\132\11\6\0\26\11\2\0\6\11\2\0\46\11\2\0" +
                    "\6\11\2\0\10\11\1\0\1\11\1\0\1\11\1\0\1\11\1\0" +
                    "\37\11\2\0\65\11\1\0\7\11\1\0\1\11\3\0\3\11\1\0" +
                    "\7\11\3\0\4\11\2\0\6\11\4\0\15\11\5\0\3\11\1\0" +
                    "\7\11\17\0\4\12\32\0\5\12\20\0\2\11\23\0\1\11\13\0" +
                    "\4\12\6\0\6\12\1\0\1\11\15\0\1\11\40\0\22\11\36\0" +
                    "\15\12\4\0\1\12\3\0\6\12\27\0\1\11\4\0\1\11\2\0" +
                    "\12\11\1\0\1\11\3\0\5\11\6\0\1\11\1\0\1\11\1\0" +
                    "\1\11\1\0\4\11\1\0\3\11\1\0\7\11\3\0\3\11\5\0" +
                    "\5\11\26\0\44\11\u0e81\0\3\11\31\0\11\11\6\12\1\0\5\11" +
                    "\2\0\5\11\4\0\126\11\2\0\2\12\2\0\3\11\1\0\137\11" +
                    "\5\0\50\11\4\0\136\11\21\0\30\11\70\0\20\11\u0200\0\u19b6\11" +
                    "\112\0\u51a6\11\132\0\u048d\11\u0773\0\u2ba4\11\u215c\0\u012e\11\2\0\73\11" +
                    "\225\0\7\11\14\0\5\11\5\0\1\11\1\12\12\11\1\0\15\11" +
                    "\1\0\5\11\1\0\1\11\1\0\2\11\1\0\2\11\1\0\154\11" +
                    "\41\0\u016b\11\22\0\100\11\2\0\66\11\50\0\15\11\3\0\20\12" +
                    "\20\0\4\12\17\0\2\11\30\0\3\11\31\0\1\11\6\0\5\11" +
                    "\1\0\207\11\2\0\1\12\4\0\1\11\13\0\12\12\7\0\32\11" +
                    "\4\0\1\11\1\0\32\11\12\0\132\11\3\0\6\11\2\0\6\11" +
                    "\2\0\6\11\2\0\3\11\3\0\2\11\3\0\2\11\22\0\3\12" +
                    "\4\0";

    /**
     * Translates characters to character classes
     */
    private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 =
            "\3\0\2\1\1\2\1\1\1\3\2\4\1\1\1\5" +
                    "\2\6\1\7\1\10\1\11\1\10\1\11\2\1\1\12" +
                    "\1\0\1\13\1\14\2\15\1\16\1\17\1\20\1\21" +
                    "\1\22\1\23\1\24\1\25\1\0\1\26\1\0\1\26" +
                    "\1\0\1\15\1\0\1\26\2\0\1\27";

    private static int[] zzUnpackAction() {
        int[] result = new int[46];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 =
            "\0\0\0\36\0\74\0\132\0\170\0\226\0\264\0\322" +
                    "\0\360\0\132\0\u010e\0\132\0\u012c\0\132\0\u014a\0\u0168" +
                    "\0\u0186\0\u01a4\0\u01c2\0\u01e0\0\u01fe\0\132\0\264\0\132" +
                    "\0\132\0\u021c\0\u023a\0\132\0\132\0\132\0\132\0\132" +
                    "\0\132\0\132\0\132\0\u0258\0\u0276\0\u0294\0\u01c2\0\u01fe" +
                    "\0\132\0\u02b2\0\u02d0\0\u02d0\0\u02ee\0\132";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[46];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;  /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();

    private static final String ZZ_TRANS_PACKED_0 =
            "\4\4\1\5\1\6\3\4\1\7\1\4\1\6\1\7" +
                    "\4\4\1\7\1\6\4\4\5\6\2\4\1\10\1\11" +
                    "\1\12\22\10\1\13\1\14\7\10\1\4\1\15\1\16" +
                    "\1\17\1\4\1\20\1\4\1\21\1\4\1\22\1\4" +
                    "\2\22\1\4\1\23\1\24\1\25\2\22\1\4\1\21" +
                    "\1\4\1\26\5\22\1\4\1\21\42\0\1\5\36\0" +
                    "\1\6\1\0\1\6\1\0\2\27\2\6\1\30\1\6" +
                    "\2\0\1\27\1\6\1\0\1\6\2\0\5\6\1\0" +
                    "\1\6\5\0\1\27\1\0\1\27\1\0\4\27\1\30" +
                    "\1\27\2\0\2\27\1\0\1\27\2\0\5\27\1\0" +
                    "\1\27\1\10\2\0\22\10\2\0\7\10\2\0\1\12" +
                    "\33\0\2\31\1\0\13\31\1\32\5\31\1\33\1\34" +
                    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\32" +
                    "\2\0\1\16\33\0\1\17\2\0\33\17\5\0\1\22" +
                    "\1\44\1\22\1\0\4\22\1\0\1\22\2\0\2\22" +
                    "\1\0\1\22\2\0\5\22\1\0\1\22\7\0\1\21" +
                    "\6\0\1\21\1\0\1\45\2\46\1\0\1\21\10\0" +
                    "\1\21\5\0\1\22\1\0\1\22\1\0\4\22\1\0" +
                    "\1\22\2\0\2\22\1\0\1\22\2\0\5\22\1\0" +
                    "\1\22\7\0\1\47\6\0\1\47\1\0\1\45\2\46" +
                    "\1\0\1\47\10\0\1\47\7\0\1\21\6\0\1\47" +
                    "\1\0\1\50\3\0\1\21\10\0\1\21\7\0\1\45" +
                    "\6\0\1\45\5\0\1\45\10\0\1\45\16\0\1\33" +
                    "\5\0\1\33\10\0\1\33\16\0\1\51\5\0\1\51" +
                    "\10\0\1\51\7\0\1\52\6\0\1\52\5\0\1\52" +
                    "\10\0\1\52\7\0\1\45\6\0\1\45\2\0\2\46" +
                    "\1\0\1\45\10\0\1\45\7\0\1\53\6\0\1\53" +
                    "\1\54\3\0\1\54\1\53\10\0\1\53\7\0\1\52" +
                    "\1\55\5\0\1\52\5\0\1\52\10\0\1\52\7\0" +
                    "\1\53\6\0\1\53\5\0\1\53\10\0\1\53\26\0" +
                    "\1\56\7\0";

    private static int[] zzUnpackTrans() {
        int[] result = new int[780];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = {
            "Unkown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
    };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 =
            "\3\0\1\11\5\1\1\11\1\1\1\11\1\1\1\11" +
                    "\7\1\1\11\1\0\2\11\2\1\10\11\1\0\1\1" +
                    "\1\0\1\1\1\0\1\11\1\0\1\1\2\0\1\11";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[46];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * the input device
     */
    private java.io.Reader zzReader;

    /**
     * the current state of the DFA
     */
    private int zzState;

    /**
     * the current lexical state
     */
    private int zzLexicalState = YYINITIAL;

    /**
     * this buffer contains the current text to be matched and is
     * the source of the yytext() string
     */
    private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

    /**
     * the textposition at the last accepting state
     */
    private int zzMarkedPos;

    /**
     * the current text position in the buffer
     */
    private int zzCurrentPos;

    /**
     * startRead marks the beginning of the yytext() string in the buffer
     */
    private int zzStartRead;

    /**
     * endRead marks the last character in the buffer, that has been read
     * from input
     */
    private int zzEndRead;

    /**
     * number of newlines encountered up to the start of the matched text
     */
    private int yyline;

    /**
     * the number of characters up to the start of the matched text
     */
    private int yychar;

    /**
     * the number of characters from the last newline up to the start of the
     * matched text
     */
    private int yycolumn;

    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;

    /**
     * zzAtEOF == true <=> the scanner is at the EOF
     */
    private boolean zzAtEOF;

    /**
     * denotes if the user-EOF-code has already been executed
     */
    private boolean zzEOFDone;

    /* user code: */

    StringBuffer string = new StringBuffer();
    boolean isMultiname = false;
    long multinameId = 0;


    /**
     * Create an empty lexer, yyrset will be called later to reset and assign
     * the reader
     */
    public Flasm3Lexer() {

    }

    public int yychar() {
        return yychar;
    }

    public int yyline() {
        return yyline + 1;
    }


    /**
     * Creates a new scanner
     * There is also a java.io.InputStream version of this constructor.
     *
     * @param in the java.io.Reader to read input from.
     */
    public Flasm3Lexer(java.io.Reader in) {
        this.zzReader = in;
    }

    /**
     * Creates a new scanner.
     * There is also java.io.Reader version of this constructor.
     *
     * @param in the java.io.Inputstream to read input from.
     */
    public Flasm3Lexer(java.io.InputStream in) {
        this(new java.io.InputStreamReader(in));
    }

    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed the packed character translation table
     * @return the unpacked character translation table
     */
    private static char[] zzUnpackCMap(String packed) {
        char[] map = new char[0x10000];
        int i = 0;  /* index in packed string  */
        int j = 0;  /* index in unpacked array */
        while (i < 1722) {
            int count = packed.charAt(i++);
            char value = packed.charAt(i++);
            do map[j++] = value; while (--count > 0);
        }
        return map;
    }


    /**
     * Refills the input buffer.
     *
     * @return <code>false</code>, iff there was new input.
     * @throws java.io.IOException if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {

        /* first: make room (if you can) */
        if (zzStartRead > 0) {
            System.arraycopy(zzBuffer, zzStartRead,
                    zzBuffer, 0,
                    zzEndRead - zzStartRead);

            /* translate stored positions */
            zzEndRead -= zzStartRead;
            zzCurrentPos -= zzStartRead;
            zzMarkedPos -= zzStartRead;
            zzStartRead = 0;
        }

        /* is the buffer big enough? */
        if (zzCurrentPos >= zzBuffer.length) {
            /* if not: blow it up */
            char newBuffer[] = new char[zzCurrentPos * 2];
            System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
            zzBuffer = newBuffer;
        }

        /* finally: fill the buffer with new input */
        int numRead = zzReader.read(zzBuffer, zzEndRead,
                zzBuffer.length - zzEndRead);

        if (numRead > 0) {
            zzEndRead += numRead;
            return false;
        }
        // unlikely but not impossible: read 0 characters, but not at end of stream
        if (numRead == 0) {
            int c = zzReader.read();
            if (c == -1) {
                return true;
            } else {
                zzBuffer[zzEndRead++] = (char) c;
                return false;
            }
        }

        // numRead < 0
        return true;
    }


    /**
     * Closes the input stream.
     */
    public final void yyclose() throws java.io.IOException {
        zzAtEOF = true;            /* indicate end of file */
        zzEndRead = zzStartRead;  /* invalidate buffer    */

        if (zzReader != null)
            zzReader.close();
    }


    /**
     * Resets the scanner to read from a new input stream.
     * Does not close the old reader.
     * <p/>
     * All internal variables are reset, the old input stream
     * <b>cannot</b> be reused (internal buffer is discarded and lost).
     * Lexical state is set to <tt>ZZ_INITIAL</tt>.
     *
     * @param reader the new input stream
     */
    public final void yyreset(java.io.Reader reader) {
        zzReader = reader;
        zzAtBOL = true;
        zzAtEOF = false;
        zzEOFDone = false;
        zzEndRead = zzStartRead = 0;
        zzCurrentPos = zzMarkedPos = 0;
        yyline = yychar = yycolumn = 0;
        zzLexicalState = YYINITIAL;
    }


    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }


    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }


    /**
     * Returns the text matched by the current regular expression.
     */
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }


    /**
     * Returns the character at position <tt>pos</tt> from the
     * matched text.
     * <p/>
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch.
     *            A value from 0 to yylength()-1.
     * @return the character at position pos
     */
    public final char yycharat(int pos) {
        return zzBuffer[zzStartRead + pos];
    }


    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }


    /**
     * Reports an error that occured while scanning.
     * <p/>
     * In a wellformed scanner (no or only correct usage of
     * yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen".
     * If this method is called, something is seriously wrong
     * (e.g. a JFlex bug producing a faulty scanner etc.).
     * <p/>
     * Usual syntax/scanner level error handling should be done
     * in error fallback rules.
     *
     * @param errorCode the code of the errormessage to display
     */
    private void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        }
        catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }


    /**
     * Pushes the specified amount of characters back into the input stream.
     * <p/>
     * They will be read again by then next call of the scanning method
     *
     * @param number the number of characters to be read again.
     *               This number must not be greater than yylength()!
     */
    public void yypushback(int number) {
        if (number > yylength())
            zzScanError(ZZ_PUSHBACK_2BIG);

        zzMarkedPos -= number;
    }


    /**
     * Resumes scanning until the next regular expression is matched,
     * the end of input is encountered or an I/O-Error occurs.
     *
     * @return the next token
     * @throws java.io.IOException if any I/O-Error occurs
     */
    public ParsedSymbol yylex() throws java.io.IOException, ParseException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;
        char[] zzCMapL = ZZ_CMAP;

        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            yychar += zzMarkedPosL - zzStartRead;

            boolean zzR = false;
            for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                 zzCurrentPosL++) {
                switch (zzBufferL[zzCurrentPosL]) {
                    case '\u000B':
                    case '\u000C':
                    case '\u0085':
                    case '\u2028':
                    case '\u2029':
                        yyline++;
                        yycolumn = 0;
                        zzR = false;
                        break;
                    case '\r':
                        yyline++;
                        yycolumn = 0;
                        zzR = true;
                        break;
                    case '\n':
                        if (zzR)
                            zzR = false;
                        else {
                            yyline++;
                            yycolumn = 0;
                        }
                        break;
                    default:
                        zzR = false;
                        yycolumn++;
                }
            }

            if (zzR) {
                // peek one character ahead if it is \n (if we have counted one line too much)
                boolean zzPeek;
                if (zzMarkedPosL < zzEndReadL)
                    zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                else if (zzAtEOF)
                    zzPeek = false;
                else {
                    boolean eof = zzRefill();
                    zzEndReadL = zzEndRead;
                    zzMarkedPosL = zzMarkedPos;
                    zzBufferL = zzBuffer;
                    if (eof)
                        zzPeek = false;
                    else
                        zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                }
                if (zzPeek) yyline--;
            }
            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];


            zzForAction:
            {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL)
                        zzInput = zzBufferL[zzCurrentPosL++];
                    else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = zzBufferL[zzCurrentPosL++];
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
                    if (zzNext == -1) break zzForAction;
                    zzState = zzNext;

                    int zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) break zzForAction;
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                case 8: {
                    return new ParsedSymbol(ParsedSymbol.TYPE_IDENTIFIER, yytext());
                }
                case 24:
                    break;
                case 21: {
                    string.append('\'');
                }
                case 25:
                    break;
                case 9: {
                    return new ParsedSymbol(ParsedSymbol.TYPE_INTEGER, new Long(Long.parseLong((yytext()))));
                }
                case 26:
                    break;
                case 3: {
                    string.append(yytext());
                }
                case 27:
                    break;
                case 13: {
                    char val = (char) Integer.parseInt(yytext().substring(1), 8);
                    string.append(val);
                }
                case 28:
                    break;
                case 5: {
                    yybegin(PARAMETERS);
                    // length also includes the trailing quote
                    if (isMultiname) {
                        return new ParsedSymbol(ParsedSymbol.TYPE_MULTINAME, new Long(multinameId));
                    } else {
                        return new ParsedSymbol(ParsedSymbol.TYPE_STRING, string.toString());
                    }
                }
                case 29:
                    break;
                case 20: {
                    string.append('\r');
                }
                case 30:
                    break;
                case 6: {
                    yybegin(YYINITIAL);
                }
                case 31:
                    break;
                case 2: {
                    yybegin(PARAMETERS);
                    return new ParsedSymbol(ParsedSymbol.TYPE_INSTRUCTION_NAME, yytext());
                }
                case 32:
                    break;
                case 7: {
                    return new ParsedSymbol(ParsedSymbol.TYPE_COMMENT, yytext().substring(1));
                }
                case 33:
                    break;
                case 11: {
                    String s = yytext();
                    return new ParsedSymbol(ParsedSymbol.TYPE_LABEL, s.substring(0, s.length() - 1));
                }
                case 34:
                    break;
                case 16: {
                    string.append('\b');
                }
                case 35:
                    break;
                case 4: {
                    throw new ParseException("Unterminated string at end of line", yyline + 1);
                }
                case 36:
                    break;
                case 10: {
                    isMultiname = false;
                    yybegin(STRING);
                    string.setLength(0);
                }
                case 37:
                    break;
                case 17: {
                    string.append('\t');
                }
                case 38:
                    break;
                case 22: {
                    return new ParsedSymbol(ParsedSymbol.TYPE_FLOAT, new Double(Double.parseDouble((yytext()))));
                }
                case 39:
                    break;
                case 14: {
                    string.append('\\');
                }
                case 40:
                    break;
                case 12: {
                    throw new ParseException("Illegal escape sequence \"" + yytext() + "\"", yyline + 1);
                }
                case 41:
                    break;
                case 23: {
                    isMultiname = true;
                    String s = yytext();
                    multinameId = Long.parseLong(s.substring(2, s.length() - 2));
                    yybegin(STRING);
                    string.setLength(0);
                }
                case 42:
                    break;
                case 18: {
                    string.append('\n');
                }
                case 43:
                    break;
                case 19: {
                    string.append('\f');
                }
                case 44:
                    break;
                case 15: {
                    string.append('\"');
                }
                case 45:
                    break;
                case 1: {
                }
                case 46:
                    break;
                default:
                    if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                        zzAtEOF = true;
                        {
                            return new ParsedSymbol(ParsedSymbol.TYPE_EOF);
                        }
                    } else {
                        zzScanError(ZZ_NO_MATCH);
                    }
            }
        }
    }


}
